### ISSUE TITLE
Water Damage

### ISSUE THREAD

**Issue by akotak** [rchatt6/cs426-Final-Project#6]
Currently, when player steps in the water, the player will take damage once.

Need to have player take damage repeatedly if the player is still in the water after a certain amount of time. For example, if player is still in water after 5 seconds, player will take more damage, not just once.

**Comment by abreyer3** [comment]
Couldn't figure out how to take damage repeatedly, so instead the player dies immediately, however, the player respawns back at the start.

**Comment by akotak** [comment]
I downloaded your project, and there's a new bug with water damage looks like.

When your armor is taken out to 0 by the zombie, and you jump in the water to die, you will respawn with your health bar at 0/100 and your armor bar is also 0/90.

There is also a bug where you walk in the water at full health, and it will take out your health to 0, but it won't respawn you unless you jump onto the water again.
