### ISSUE TITLE
Zombie Sounds

### ISSUE THREAD

**Issue by akotak** [rchatt6/cs426-Final-Project#9]
Zombie sounds effects still play in the background even when you're far away from the zombie.

Need to make it so zombie sound effects stop when you're away a certain distance.

**Comment by abreyer3** [comment]
Strange... Zombie sfx stop for me when I'm far enough. Haven't made any changes to that.

**Comment by akotak** [comment]
I downloaded your latest project, but it looks like the zombie SFX still plays in the background for some reason when I run it, even though I walked away to another island.

Can have Rahul confirm if it works for him because maybe it's just me.

**Comment by akotak** [comment]
Fixed. Changed zombie volume rolloff in 3D sound settings to Linear rolloff.
